name: Francinette + Norminette + Test 4 Only

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  tests:
    name: Run Francinette workflow (tester 4 only)
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Install system dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git make clang python3 python3-venv python3-pip

      # 3. Cache Francinette
      - name: Cache Francinette
        uses: actions/cache@v4
        with:
          path: ~/francinette
          key: francinette-${{ runner.os }}-v1

      # 4. Setup Francinette
      - name: Setup Francinette
        run: |
          if [ ! -d ~/francinette ]; then
            git clone https://github.com/xicodomingues/francinette.git ~/francinette
          fi
          cd ~/francinette
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install norminette
          chmod +x tester.sh

      # 5. Move to project root
      - name: Move to project root
        run: |
          cd $GITHUB_WORKSPACE
          ls -la

      # 6. Run Francinette for tester 4 only
      - name: Run Francinette tester 4
        run: |
          cd $GITHUB_WORKSPACE
          source ~/francinette/venv/bin/activate
          ~/francinette/tester.sh . -t 4

      # 7. Run Norminette
      - name: Run Norminette
        run: |
          cd $GITHUB_WORKSPACE
          source ~/francinette/venv/bin/activate
          norminette .
