name: Francinette Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  francinette:
    name: Run Francinette Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git make clang python3 python3-venv python3-pip

      - name: Clone and set up Francinette
        run: |
          git clone https://github.com/xicodomingues/francinette.git ~/francinette
          cd ~/francinette
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          chmod +x tester.sh

      - name: Check repo structure
        run: |
          echo "Workspace path: $GITHUB_WORKSPACE"
          ls -R $GITHUB_WORKSPACE

      - name: Run Francinette on libft
        run: |
          cd ~/francinette
          source venv/bin/activate
          ./tester.sh $GITHUB_WORKSPACE
