name: Francinette CI - Docker

# Run workflow on push or pull requests to main branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  francinette:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Pull Francinette Docker image (public, no login needed)
      - name: Pull Francinette Docker image
        run: docker pull jaymanani/francinette:latest

      # 3️⃣ Run Francinette container on your repo
      - name: Run Francinette tests
        run: |
          docker run --rm -t \
            -v ${{ github.workspace }}:/project \
            -w /project \
            jaymanani/francinette:latest
