name: Francinette Tests

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  francinette:
    name: Run Francinette on libft
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git make clang python3 python3-venv python3-pip

      - name: Clone and setup Francinette
        run: |
          git clone https://github.com/xicodomingues/francinette.git ~/francinette
          cd ~/francinette
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          chmod +x tester.sh

      - name: Run Francinette inside libft repo
        run: |
          cd $GITHUB_WORKSPACE
          echo "Current dir: $(pwd)"
          ls -l
          cd ~/francinette
          source venv/bin/activate
          ./tester.sh .
