name: libftTester CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test_libft:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout your libft repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Install system dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git make clang valgrind

      # 3. Clone Tripouille's libftTester
      - name: Clone libftTester
        run: |
          git clone https://github.com/Tripouille/libftTester.git ~/libftTester

      # 4. Configure the tester
      - name: Configure libftTester
        run: |
          cd ~/libftTester
          # Set LIBFT_PATH to your repo
          sed -i "s|LIBFT_PATH=.*|LIBFT_PATH=$GITHUB_WORKSPACE|" Makefile

      # 5. Run all mandatory + bonus tests
      - name: Run libftTester
        run: |
          export TERM=xterm
          cd ~/libftTester
          make a

      - name: Norminette Check
        run: |
          pip install norminette
          norminette $GITHUB_WORKSPACE