name: Francinette Tests

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  francinette:
    name: Run Francinette on libft
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Install dependencies for Francinette
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git make clang python3 python3-venv python3-pip

      # 3. Clone and setup Francinette
      - name: Setup Francinette
        run: |
          git clone https://github.com/xicodomingues/francinette.git ~/francinette
          cd ~/francinette
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          chmod +x tester.sh

      # 4. Run Francinette in your libft folder
      - name: Run Francinette
        run: |
          cd $GITHUB_WORKSPACE
          pwd
          ls -l
          source ~/francinette/venv/bin/activate
          ~/francinette/tester.sh .
