name: Francinette + Norminette + libft Testers

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run full libft workflow

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git make clang python3 python3-venv python3-pip

      - name: Cache Francinette
        uses: actions/cache@v4
        with:
          path: ~/francinette
          key: francinette-${{ runner.os }}-v1

      - name: Setup Francinette
        run: |
          if [ ! -d ~/francinette ]; then
            git clone https://github.com/xicodomingues/francinette.git ~/francinette
          fi
          cd ~/francinette
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install norminette
          chmod +x tester.sh

      - name: Move to project root
        run: |
          cd $GITHUB_WORKSPACE
          ls -la

      - name: Ensure libft‑tester is present
        run: |
          cd ~/francinette/testers
          if [ ! -d libft ]; then
            echo "libft tester folder missing!"
            exit 1
          fi
          echo "libft tester folder found."

      - name: Run Francinette with libft testers
        run: |
          cd $GITHUB_WORKSPACE
          source ~/francinette/venv/bin/activate
          ~/francinette/tester.sh . --tester libft
          
      - name: Run Norminette
        run: |
          cd $GITHUB_WORKSPACE
          source ~/francinette/venv/bin/activate
          norminette .
