name: Norminette Workflow

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  tests:
    name: Run Norminette workflow
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Install system dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git make clang python3 python3-venv python3-pip

      # 3. Install Norminette
      - name: Install Norminette
        run: |
          pip install norminette

      # 4. Move to project root
      - name: List all the Files
        run: |
          cd $GITHUB_WORKSPACE
          ls -la

      # 5. Run Norminette
      - name: Run Norminette
        run: |
          cd $GITHUB_WORKSPACE
          norminette .
